version: '3.8'

services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/otomatik-frontend:${IMAGE_TAG:-latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - VITE_FLUTTERWAVE_PUBLIC_KEY=${VITE_FLUTTERWAVE_PUBLIC_KEY}
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    image: ${DOCKERHUB_USERNAME}/otomatik-backend:${IMAGE_TAG:-latest}
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - VITE_FLUTTERWAVE_PUBLIC_KEY=${VITE_FLUTTERWAVE_PUBLIC_KEY}
    volumes:
      - ./backend/bookings.db:/app/bookings.db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 