name: Continuous Deployment

on:
  release:
    types: [published]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_TAG: ${{ github.event.release.tag_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment files
        run: |
          chmod +x .github/scripts/create-env.sh
          .github/scripts/create-env.sh
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Frontend
      - name: Extract metadata for Frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/otomatik-frontend
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            latest

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push Backend
      - name: Extract metadata for Backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/otomatik-backend
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            latest

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Deploy to production server
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          # Create deployment directory if it doesn't exist
          ssh $SERVER_USER@$SERVER_HOST "mkdir -p $DEPLOY_PATH"

          # Ensure Docker network exists
          ssh $SERVER_USER@$SERVER_HOST "docker network create app-network || true"
          
          # Copy deployment files
          scp docker-compose.yml $SERVER_USER@$SERVER_HOST:$DEPLOY_PATH/
          
          # Generate .env file on the server
          ssh $SERVER_USER@$SERVER_HOST "cd $DEPLOY_PATH && echo '${{ secrets.ENV_FILE }}' | base64 -d > .env"
          
          # Deploy using Docker Compose
          ssh $SERVER_USER@$SERVER_HOST "cd $DEPLOY_PATH && \
            export IMAGE_TAG=${{ env.IMAGE_TAG }} && \
            export DOCKERHUB_USERNAME=${{ env.DOCKERHUB_USERNAME }} && \
            docker compose pull && \
            docker compose up -d && \
            docker system prune -f"

      - name: Verify Deployment
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          # Wait for services to be healthy
          ssh $SERVER_USER@$SERVER_HOST "docker compose ps --format json" | grep -q "running" || exit 1
          echo "✅ Deployment successful - Version ${{ env.IMAGE_TAG }}" 